# Generated by Django 6.0.1 on 2026-03-16 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionpaper_questionpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenquiry',
            name='lead_type',
            field=models.CharField(choices=[('new', 'New'), ('dnp', 'DNP'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('trainer', 'Trainer'), ('cre', 'CRE')], default='admin', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainerSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='core.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('trainer', 'department', 'course'), name='unique_trainer_specialization')],
            },
        ),
    ]
